@startuml
'https://plantuml.com/state-diagram

hide empty description

scale 350 width
[*] --> オープン: 欠陥レポート着手開始
オープン -> 分析_割当: 開発担当者に割当
分析_割当 --> 重複
オープン --> 重複
重複 --> [*]: 却下

分析_割当 --> 延期: あとでやる
分析_割当 -> 修正待ち: 開発者修正着手
修正待ち --> 延期: あとでやる
延期 -> 分析_割当: 開発担当者に割当

修正待ち -> 確認テスト待ち: 修正完了
確認テスト待ち --> クローズ: 故障の解決確認

確認テスト待ち --> 再オープン: 故障解決してない
再オープン -> 分析_割当: 差し戻し

クローズ --> [*]: 終了


@enduml
