name: build and deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Gatsby Environment
        uses: actions/checkout@v2
        with:
          repository: "wand2016/study_gatsby"
      - name: Checkout Contents
        uses: actions/checkout@v2
        with:
          path: "content/blog"
      - name: cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: install nodejs dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: cache gatsby
        uses: actions/cache@v2
        with:
          path: |
            .cache
          key: "fixed"
      - name: build and deploy
        run: ./deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_ALGOLIA_INDEX: ${{ secrets.GATSBY_ALGOLIA_INDEX }}
        timeout-minutes: 10
